apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: horrible-mole-go 
  janus-idp.io/tekton: horrible-mole-go
  backstage.io/kubernetes-id: horrible-mole-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: horrible-mole-go
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  